#! /bin/bash
# Capture BIT.TRIP.Runner using GLC.
# by Taylor "Ripps" LeMasurier-Wren <ripps818@gmail.com>
DIR="$(pwd)"
cd /opt/bit.trip.runner

GLCARGS="-l $DIR/bittriprunner-glc.log -v 3 -f 30 -e bgr --uncompressed=50 --compressed=100 -s -p -o $DIR/bittriprunner.glc"
GAMEEXE="/opt/bit.trip.runner/bit.trip.runner"

# Record audio
record-microphone $DIR/bittriprunner.voice.wav &

# STar game
echo "glc-capture $GLCARGS $GAMEEXE $@"
glc-capture $GLCARGS $GAMEEXE "$@"
killall parec
