#! /bin/bash
# Capture BIT.TRIP.Runner using GLC.
# by Taylor "Ripps" LeMasurier-Wren <ripps818@gmail.com>
DIR="$(pwd)"
cd /opt/bittriprunner

GLCARGS="-l $DIR/bittriprunner-glc.log -v 3 -f 60 --uncompressed=100 --unscaled=100 --compressed=200 -s -p -o $DIR/bittriprunner.glc"
GAMEEXE="/opt/bit.trip.runner/bit.trip.runner"

# Record audio
record-microphone "$DIR/bittriprunner.voice.wav" &

# STar game
echo "glc-capture $GLCARGS $GAMEEXE $@"
glc-capture $GLCARGS "$GAMEEXE" "$@"
killall parec
