#! /bin/bash
# Capture Java OpenGL from Minecraft Feed the Beast modpacks
# using GLC.
# by Taylor "Ripps" LeMasurier-Wren <ripps818@gmail.com>

GAMEJAR="/home/ripps/bin/FTB_Launcher.jar"
GLCARGS="-l ftb-glc.log -v 3 -i --disable-audio -b back -o ftb.glc --uncompressed=100 --unscaled 100 --compressed=200"

# Record audio
record-monitor ftb.monitor.wav &
record-microphone ftb.voice.wav &

# Start game
echo "glc-capture $GLCARGS java -jar $GAMEJAR"
glc-capture $GLCARGS java -jar $GAMEJAR

killall parec
