#! /bin/bash
# Capture Java OpenGL from Minecraft Feed the Beast modpacks using GLC.
# by Taylor "Ripps" LeMasurier-Wren <ripps818@gmail.com>

GAMEJAR="/usr/share/feedthebeast/feedthebeast.jar"
GLCARGS="-l ftb-glc.log -v 3 -i -p -b back -o ftb.glc"
LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$JAVA_HOME/lib/amd64/:$JAVA_HOME/lib/i386/:$JAVA_HOME/jre/lib/amd64/:$JAVA_HOME/jre/lib/i386/"

# Record audio
record-microphone ftb.voice.wav &

# fix for users of special IM modules
unset XMODIFIERS GTK_IM_MODULE QT_IM_MODULE

# Start game
echo "glc-capture $GLCARGS java -jar $GAMEJAR $@"
glc-capture $GLCARGS java -Xmx1024M -Xms512M -jar $GAMEJAR "$@"

killall parec
