#! /bin/bash
# use 32-bit version of glc to capture Team Fortess 2 beta for Linux
# Steam client must be running.
# by Taylor "Ripps" LeMasurier-Wren <ripps818@gmail.com>
DIR=$(echo $PWD)

GAMEROOT="/home/ripps/Steam/SteamApps/ripps818/Team Fortress 2"
STEAMPATH="/home/ripps/Steam/ubuntu12_32"
GAMEEXE=hl2_linux
cd "$GAMEROOT"

export SteamAppId=440
export LD_LIBRARY_PATH=bin:"${STEAMPATH}":/usr/lib32:$LD_LIBRARY_PATH
#export LD_PRELOAD=$(dirname ${STEAMPATH})/gameoverlayrenderer.so

# Enable Nvidia Optimizations
export __GL_THREADED_OPTIMIZATIONS=1

echo "${GAMEROOT}/${GAMEEXE}"
#record-monitor "${DIR}}"/tf2-pa.wav &
chmod +x ${GAMEEXE}
/usr/bin/glc-capture32 -l "${DIR}"/tf2-glc.log -v 3 -i --disable-audio -b back -z lzo -o "${DIR}"/tf2.glc ${GAMEEXE} -game tf -steam -novid
#kill $!

